version: "3.5"

services:
  api:
    image: vindr/vinlab-api
    container_name: vinlab-api
    ports:
      - 8080
    environment:
      API_ENV: production
      DEBUG: "DEBUG"
      GIN_MODE: "release"
      WEBSERVER__API_KEY: ${API_KEY}
      ELASTICSEARCH__URI: ${ES_URI}
      KEYCLOAK__URI: ${KEYCLOAK_URI}
      KEYCLOAK__MASTER_REALM: master
      KEYCLOAK__APP_REALM: ${KEYCLOAK_APP_REALM}
      KEYCLOAK__ADMIN_USERNAME: admin
      KEYCLOAK__ADMIN_PASSWORD: admin
      MINIO__URI: ${MINIO_URI}
      MINIO__ACCESS_KEY_ID: ${MINIO_ACCESS_KEY}
      MINIO__SECRET_ACCESS_KEY: ${MINIO_SECRET_KEY}
      MINIO__BUCKET_NAME: vinlab-label-exported
      REDIS__URI: ${REDIS_URI}
      ORTHANC__URI: ${ORTHANC_URI}
      ID_GENERATOR__URI: ${IDGEN_URI}
    volumes:
      - ./conf/api:/opt/app/conf
      - ./permissions.csv:/opt/app/conf/permissions.csv
    restart: always
    depends_on:
      - es
      - minio
      - idgen

  idgen:
    image: vindr/vinlab-idgen
    container_name: vinlab-idgen
    environment:
      GIN_MODE: "release"
      RQLITE__URI: "${RQLITE_URI}"
    ports:
      - 8080
    restart: always
    depends_on:
      - rqlite

  uploader:
    image: vindr/vinlab-dicom-uploader
    container_name: vinlab-uploader
    ports:
      - 8080
    environment:
      GUNICORN_WORKERS: "4"
      GUNICORN_PORT: "8080"
      ENVVAR_PREFIX_FOR_DYNACONF: APP
      ENV_FOR_DYNACONF: production
      APP_ORTHANC_API_URI: ${ORTHANC_URI}
      APP_REDIS_URI: ${REDIS_URI}
      APP_REDIS_CACHE_TIME: "600"
      APP_ELASTICSEARCH_HOST: ${ES_URI}
      APP_ES_STUDIES_INDEX_PREFIX: vinlab_studies
      APP_ES_PROJECTS_INDEX_PREFIX: vinlab_projects
      APP_VINDR_LAB_API_KEY: ${API_KEY}
      APP_VINDR_LAB_URI: ${API_URI}
      APP_ID_GENERATOR_URI: ${IDGEN_URI}
      APP_PUBLIC_KEY_PATH: "key.pub"
      APP_KC_VERIFY_AUDIENCE: "vinlab-backend"
      APP_KEYCLOAK_HOST: ${KEYCLOAK_URI}/auth
      APP_KEYCLOAK_REALM: ${KEYCLOAK_APP_REALM}
    restart: always
    depends_on:
      - es
      - orthanc
      - redis
      - api
      - idgen
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: 20m

  dashboard:
    image: vindr/vinlab-dashboard
    container_name: vinlab-dashboard
    ports:
      - 80
    environment:
      PUBLIC_URL: "/dashboard"
      SERVER_BASE_URL: "${BASE_URI}"
      MEDICAL_VIEWER_URL_PREFIX: "/medical-view"
      DASHBOARD_URL_PREFIX: "/dashboard"
      OIDC_CLIENT_ID: "vinlab-frontend"
      OIDC_AUTHORIZATION_URI: "${BASE_URI}/auth/realms/${KEYCLOAK_APP_REALM}/protocol/openid-connect/auth"
      OIDC_ACCESS_TOKEN_URI: "${BASE_URI}/auth/realms/${KEYCLOAK_APP_REALM}/protocol/openid-connect/token"
      OIDC_REDIRECT_URI: "${BASE_URI}/dashboard"
      OIDC_LOGOUT_URI: "${BASE_URI}/auth/realms/${KEYCLOAK_APP_REALM}/protocol/openid-connect/logout"
      OIDC_USERINFO_ENDPOINT: "${BASE_URI}/auth/realms/${KEYCLOAK_APP_REALM}/protocol/openid-connect/userinfo"
      OIDC_AUDIENCE: "vinlab-backend"
    restart: always
    depends_on:
      - keycloak
      - api

  viewer:
    image: vindr/vinlab-viewer
    container_name: vinlab-viewer
    ports:
      - 80
    environment:
      SERVER_BASE_URL: ${BASE_URI}
      MEDICAL_VIEWER_URL_PREFIX: /medical-view
      DASHBOARD_URL_PREFIX: /dashboard
      OIDC_CLIENT_ID: vinlab-frontend
      OIDC_AUTHORIZATION_URI: ${BASE_URI}/auth/realms/${KEYCLOAK_APP_REALM}/protocol/openid-connect/auth
      OIDC_ACCESS_TOKEN_URI: ${BASE_URI}/auth/realms/${KEYCLOAK_APP_REALM}/protocol/openid-connect/token
      OIDC_REDIRECT_URI: ${BASE_URI}/dashboard
      OIDC_LOGOUT_URI: ${BASE_URI}/auth/realms/${KEYCLOAK_APP_REALM}/protocol/openid-connect/logout
      OIDC_USERINFO_ENDPOINT: ${BASE_URI}/auth/realms/${KEYCLOAK_APP_REALM}/protocol/openid-connect/userinfo
      OIDC_AUDIENCE: "vinlab-backend"
    restart: always
    depends_on:
      - api
      - orthanc

  minio:
    image: minio/minio:RELEASE.2022-05-04T07-45-27Z
    container_name: vinlab-minio
    volumes:
      - ./data/minio:/data
    command: "minio server /data --console-address \":9001\""
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
    ports:
      - 9000
    restart: always
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: 20m

  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.2
    container_name: vinlab-es
    environment:
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - 9200
    restart: always
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: 20m
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch/data

  orthanc:
    image: osimis/orthanc
    container_name: vinlab-orthanc
    environment:
      ORTHANC__AUTHENTICATION_ENABLED: "false"
      ORTHANC__DICOM_WEB__ENABLE: "true"
      ORTHANC__DICOM_WEB__ROOT: "/dicom-web"
      ORTHANC__DICOM_WEB__ENABLE_WADO: "true"
      ORTHANC__DICOM_WEB__WADO_ROOT: "/wado"
    volumes:
      - ./data/orthanc:/var/lib/orthanc/db
    ports:
      - 4242
      - 8042
    restart: always
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: 20m

  redis:
    image: redis:latest
    container_name: vinlab-redis
    ports:
      - 6379
    restart: always
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: 20m

  keycloak:
    image: jboss/keycloak:11.0.2
    container_name: vinlab-keycloak
    command:
      [
        "-Djboss.http.port=9090",
        "-Dkeycloak.profile.feature.upload_scripts=enabled",
      ]
    ports:
      - 9090
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      PROXY_ADDRESS_FORWARDING: "true"
    volumes:
      - ./keycloak-db:/opt/jboss/keycloak/standalone/data
    restart: always
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: 20m

  rqlite:
    image: rqlite/rqlite:5.10.2
    container_name: vinlab-rqlite
    ports:
      - 4001
      - 4002
    volumes:
      - ./data/rqlite:/rqlite/file/data
    restart: always
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: 20m

  nginx:
    image: nginx:latest
    container_name: vinlab-nginx
    volumes:
      - ./conf/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    restart: always
    ports:
      - 8080:8080
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: 20m

volumes:
  data01:
    driver: local
