[webserver]
port = 8088

[elasticsearch]
uris = ["http://0.0.0.0:9200"]
# uris = ["http://es01:9200"]
annotation_index_prefix = "vinlab_annotations"
label_index_prefix = "vinlab_labels"
study_index_prefix = "vinlab_studies"
project_index_prefix = "vinlab_projects"
label_export_index_prefix = "vinlab_label_exports"
object_index_prefix = "vinlab_objects"
session_index_alias = "vinlab_sessions"
label_group_index_prefix = "vinlab_label_groups"
task_index_prefix = "vinlab_tasks"
account_index_prefix = "vinlab_accounts"
counter_index_prefix = "vinlab_counter"

[minio]
uri = "0.0.0.0:9000"
# uri = "minio:9000"
access_key_id="vindr-lab-api"
secret_access_key="vindr-lab-api"
bucket_name="vinlab-label-exported"

[keycloak]
uri = "http://0.0.0.0:9090"
master_realm = "master"
app_realm = "vinlab"
admin_username = "admin"
admin_password = "admin"
